name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run CI/CD
        run: echo "CI/CD Pipeline is running successfully!"

      - name: Build
        run: echo "Build completed successfully!"

      - name: Deploy
        run: echo "Deployment completed successfully!"
